export const FETCH_TEMPLATE_START = "FETCH_TEMPLATE_START";
export const FETCH_TEMPLATE_SUCCESS = "FETCH_TEMPLATE_SUCCESS";
export const FETCH_TEMPLATE_FAIL = "FETCH_TEMPLATE_FAIL";

export const FETCH_HOUSE_DATA_START = "FETCH_HOUSE_DATA_START";
export const FETCH_HOUSE_DATA_SUCCESS = "FETCH_HOUSE_DATA_SUCCESS";
export const FETCH_HOUSE_DATA_FAIL = "FETCH_HOUSE_DATA_FAIL";

export const CHANGE_TEMPLATE = "CHANGE_TEMPLATE";
